### ISSUE TITLE
new_lineno - error

### ISSUE THREAD

**Issue by misteral** [mmozuras/pronto-poper#4]
pronto is last from githab

```
NoMethodError: undefined method `new_lineno' for nil:NilClass
/home/ror/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pronto-c0ef0ff78873/lib/pronto/formatter/gitlab_formatter.rb:5:in `block in format'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pronto-c0ef0ff78873/lib/pronto/formatter/gitlab_formatter.rb:5:in `uniq'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pronto-c0ef0ff78873/lib/pronto/formatter/gitlab_formatter.rb:5:in `format'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/pronto-c0ef0ff78873/lib/pronto.rb:37:in `run'
/data/happy_club/lib/tasks/code_analize.rake:7:in `block (2 levels) in <top (required)>'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/ror/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/ror/.rbenv/versions/2.2.2/bin/rake:23:in `load'
/home/ror/.rbenv/versions/2.2.2/bin/rake:23:in `<main>'
```
objects in message
```
#<Pronto::Message:0x007fa86d9192c8
  @commit_sha="82e6193b79f1e0376d22fc0ba0595821c3a84291",
  @level=:warning,
  @line=nil,
  @msg="Git commit message summary (first line) should be 50 chars or less",
  @path=nil>,
 #<Pronto::Message:0x007fa86d919188
  @commit_sha="eeada070da2396b20f48d35aae6cdb8309c49144",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d919098
  @commit_sha="882ef0563910d99d6015e09208f30255067e43fa",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918ff8
  @commit_sha="fff34763950e0cada0576fd72fa9df8c48f1e227",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918f08
  @commit_sha="5d4e790659da83716e2a839e19b8f838e82931a5",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918e90
  @commit_sha="68885e6564fbd17aa9a13dc734ddf048d7918eab",
  @level=:warning,
...skipping...
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918ff8
  @commit_sha="fff34763950e0cada0576fd72fa9df8c48f1e227",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918f08
  @commit_sha="5d4e790659da83716e2a839e19b8f838e82931a5",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918e90
  @commit_sha="68885e6564fbd17aa9a13dc734ddf048d7918eab",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918df0
  @commit_sha="7aff009faa3290f105ad0b9c05b8a926e6983ebb",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918d50
  @commit_sha="c8e0580508ff2f40df3f22aed3bb0f63758ced3a",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>]
...skipping...
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918ff8
  @commit_sha="fff34763950e0cada0576fd72fa9df8c48f1e227",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918f08
  @commit_sha="5d4e790659da83716e2a839e19b8f838e82931a5",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918e90
  @commit_sha="68885e6564fbd17aa9a13dc734ddf048d7918eab",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918df0
  @commit_sha="7aff009faa3290f105ad0b9c05b8a926e6983ebb",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>,
 #<Pronto::Message:0x007fa86d918d50
  @commit_sha="c8e0580508ff2f40df3f22aed3bb0f63758ced3a",
  @level=:warning,
  @line=nil,
  @msg="Git commit message should start with a capital letter",
  @path=nil>]

```

**Comment by mmozuras** [comment]
Fixed. Will be released with next version of Pronto.

https://github.com/mmozuras/pronto/commit/64fa0e203a34c21458a3734fd382ae7a687857f6
