### ISSUE TITLE
Running 'pronto run -i' without any .rb file changed raises an error

### ISSUE THREAD

**Issue by abinoam** [mmozuras/pronto-poper#6]
```
abinoam$ pronto run -i
/Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/runner.rb:26:in `repo_path': undefined method `repo' for nil:NilClass (NoMethodError)
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-poper-0.6.0/lib/pronto/poper.rb:9:in `run'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/runners.rb:16:in `block in run'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/runners.rb:13:in `each'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/runners.rb:13:in `run'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto.rb:42:in `run'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/cli.rb:52:in `run'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/bin/pronto:6:in `<top (required)>'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `load'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `<main>'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/abinoam/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

If I introduce a change in any ruby file than the error disappears.

**Comment by abinoam** [comment]
```ruby
    def repo_path
      ruby_patches.first.repo.path
    end
```

ruby_patches is probably an empty Array ([]) then #first returns nil.
nil doesn't respond to #repo and the error raises.

**Comment by mmozuras** [comment]
@abinoam should be fixed in next release with your own PR: https://github.com/mmozuras/pronto/pull/153

Right? 😄

**Comment by mmozuras** [comment]
Closing as it was (presumably fixed). @abinoam please re-open if you still encounter this issue 🙇.
